# Generated by Django 5.0.4 on 2024-04-15 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MachineLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('machine', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('workOrder', models.CharField(max_length=100)),
                ('serialNumber', models.CharField(max_length=100)),
                ('partNumber', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('notes', models.TextField()),
                ('setupTime', models.CharField(max_length=100)),
                ('machiningTime', models.CharField(max_length=100)),
            ],
        ),
    ]
